name: Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4

      - name: Replace package json key value
        uses: restackio/update-json-file-action@2.1
        with:
          file: package.json
          fields: "{\"dependencies.my-awesome-library\": \"NEW_VALUE\"}" 

      - name: Read package json
        id: package
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: package.json
      
      - name: Echo package.json
        run: echo "${{ steps.package.outputs.content }}"

      - name: Build an artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          retention-days: 5
          path: ./dist/
